### PR TITLE
Editorial changes for PER, CP, E, and T.

### PR DESCRIPTION
**Pull request by tituswinters**
As before, hopefully non-controversial stuff, but let me know if anything should be discussed individually and I'll split it out.

### CODE REVIEW

**Comment by cubbimew** [comment]
Out of curiosity, which resource acquisitions never fail?

**Comment by tituswinters** [comment]
Mutex acquisition with no timeout?  Allocation when the allocator kills the process instead of throwing?

**Comment by cubbimew** [comment]
mutex acquisition can fail in a number of ways, which are mapped to C++ exceptions by §30.4.1.2[thread.mutex.requirements.mutex]/13. Whether or not error handling by crashing is relevant to E.6, it does not seem like an editorial change.

**Comment by tituswinters** [comment]
That would seem to be a question for the editors.  Speaking from Google internal experience - we do a lot of RAII in an exception-free environment, for allocation and resource aquire/release (mutexes or otherwise).

**Comment by blakehawkins** [comment]
Suggest splitting the clear grammar improvements into a separate commit from the changes that need discussion. That should ease fixups when there's a conflict.

**Comment by AndrewPardoe** [comment]
This set of changes is good. With regards to link 9962, we'll change it to read as follows: 

Only the first of these reasons is fundamental, so whenever possible, use exceptions to implement RAII. Or design your resource handles to never fail.

**Pull request merged**
