### PR TITLE
fix markdown style and code snippets

### PR DESCRIPTION
**Pull request by tkruse**
Hi,

i started extracting and compiling / linting the C++ snippets. The PR lists minor things I found in the process. I am not 100% sure about my C++ fixes.

### CODE REVIEW

**Comment by tkruse** [comment]
I can squash if you like

**Comment by skendrcks1** [comment]
Huh

**Comment by tkruse** [comment]
I can reduce the number of commits, for a nicer history. I kept adding smaller things as I saw them.

**Comment by tkruse** [comment]
rebased

**Comment by gdr-at-ms** [comment]
I like the general direction and the fixes.  However, many of the examples are not necessarily intended to be complete statements; e.g. les conditionals do not need to be completed with empty statements.  Sometimes we leave `???` as a reminder to complete a work item.  They do no need to be in comments.
Could your resubmit this patch taking into account this feedback?  Thanks!

**Comment by tkruse** [comment]
I will split the PR into controversial additions and simple ones. Then we can discuss.

**Comment by tkruse** [comment]
superceded by #210 and #211

**Comment by skendrcks1** [comment]
Hi isocpp/CppCoreGuidel,

I'd like to add you to my professional network on LinkedIn.

- sylvester

Confirm that you know sylvester: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=18MjSi1J&invitationId=6140201177880543232&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eioiuxhtu%7Epn








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ioiuxhtu-pn&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGnUYOWR1AZJwAAAVTZgkDYPXAshej68dpT1Oqq61EeJYBZ9p1qMVbURiDQqmLDLHmigQ23B137n7rHWkhewx0VMkECE_9iA1auoQq0D0Lypc-Afd3tJ2Wbn3RiPtJ9jJg-iCspRZW8tIBc6WawQjQ2kkgzcAqltpbPKlohog2bAe6SLC1GG05-xFmFVFkMu6bA&eid=0-ioiuxhtu-pn


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ioiuxhtu-pn&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by skendrcks1** [comment]
sylvester Kendricks would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=y3vtgj-iooin7di-qy&t=ssuw&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=18MjSi1J&invitationId=6140201177880543232

View sylvester Kendricks&#39;s profile: https://www.linkedin.com/e/v2?e=y3vtgj-iooin7di-qy&t=ssuw&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=18MjSi1J&invitationId=6140201177880543232





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=y3vtgj-iooin7di-qy&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=y3vtgj-iooin7di-qy&loid=AQE9ga6XsdlFMAAAAVTvF7tf6wW74g0SSbnJthyBR6_MdkZ5kQHf6oa0-ewwtHJhTXjpiVAxfr3ftHuLQa0CyTv9gLBFgQFHFsXE0O4E0c9Aq1UgGe78k2mjFxvwwJ8wQajYWcGdGWyWElZlPj0AJxtzr7xVHarqGDW9qncNyN93BsWxN1Dp6Pt1jpQC7-lI1foF

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=y3vtgj-iooin7di-qy&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by skendrcks1** [comment]
sylvester Kendricks would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=y3vtgj-ioy1o8y4-4u&t=ssuw&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=18MjSi1J&invitationId=6140201177880543232

View sylvester Kendricks&#39;s profile: https://www.linkedin.com/e/v2?e=y3vtgj-ioy1o8y4-4u&t=ssuw&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=18MjSi1J&invitationId=6140201177880543232





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=y3vtgj-ioy1o8y4-4u&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=y3vtgj-ioy1o8y4-4u&loid=AQG3aeMegHi0cAAAAVURAe279l22EROFAE8yEKpG6zSUtEwjqVVqmLu9GNOR2azUUCHktzc1RHKibv_OJGSkg67Uw40w9fPD2nouR3EsIW3tLHYeBq50uyItOapvPj4xAaK0WIiZ9cLwwAfDI2ruAh3s5Ge9v80z8IJemXVgL_IV5H5rix0lcdyhuoXAdKUphX8h

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=y3vtgj-ioy1o8y4-4u&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request closed without merging**
