### PR TITLE
ES.103 examples updated, addresses Issue #1656

### PR DESCRIPTION
**Pull request by dboyce-gh**
Fixes incorrect bad example and clarifies why examples are bad.  Addresses Issue #1656

### CODE REVIEW

**Comment by dboyce-gh** [comment]
Thanks, @markyin.

I’m not sure what (if anything) I need to do next.  I assume that an authorised maintainer will merge the request into master at some point.  Will he/she close the issue at that point, or is that something I need to do when it has been merged?

David

**Comment by beinhaerter** [comment]
@dboyce-gh Just wait. Normally small changes are merged by a maintainer in a timely manner. Some changes are first discussed in a commitee meeting and then Herb Sutter comes back to these PRs after the meeting.

So nothing to do on your side. Just wait for the PR to be merged. When it is merged you can delete the branch and the fork if you don't need it anymore.

**Comment by jwakely** [comment]
> Some changes are first discussed in a commitee meeting

To be clear, those are meetings of the C++ Core Guidelines editors, not the C++ committee.

**Comment by hsutter** [comment]
Editors call: Thanks!

**Pull request merged**
