### PR TITLE
correct a word

### PR DESCRIPTION
**Pull request by michaelz85**
I think there should be a 'which' instead of the 'the' in the edited sentence.

### CODE REVIEW

**Comment by cubbimew** [comment]
This may bait English language-lawyers, but I bet "that", rather than "which", was the intent. There is "Flag classes that are copyable" elsewhere.

**Comment by michaelz85** [comment]
As English is just a second language for me, I had to read up on which vs. that. 
I agree, there should be a "that" not a which.

**Comment by michaelz85** [comment]
I'm guessing this pull-request should be closed and a new one has to be created?

**Comment by jwakely** [comment]
> a new one has to be created?

No, you can just force-push a different commit to the same branch and re-use the same pull request. It might even be possible to edit it via the github web UI.

**Pull request closed without merging**
