### PR TITLE
Minor markdown adjustments on talks' README

### PR DESCRIPTION
**Pull request by engreimor**
Have fixed/formatted markup for links.

I think its better looking this way.

### CODE REVIEW

**Comment by thecoshman** [comment]
Nice clean up, but the commits should be cleaned up, it just pollutes the history.

**Comment by engreimor** [comment]
what did you mean by clean up the commits? can you help me sending a 'clean' one?

**Comment by thecoshman** [comment]
You have ended up using three commits to do this. You should first make sure that your fork is up-to-date with the isocpp repo. Then make your own commit to make these changes, with a good message, then push to your repo on github and make a pull request for that one commit.

you might be able to mess around with re-basing and squashing and all sorts of nonsense, but it's such a tiny change, probably easier to just start over. Trying to explain how to use git, github and pull requests is beyond a comment here.

**Comment by engreimor** [comment]
thanks, you are right. i will start over since I have the file stashed.

**Pull request closed without merging**
