### PR TITLE
Fix grammar in C.60

### PR DESCRIPTION
**Pull request by david-mitchell**

### CODE REVIEW

**Comment by gdr-at-ms** [comment]
If you have series of simple typo corrections like this, it is OK to batch them.
It when the batch comprises 'unrelated' topics that it becomes difficult to track.
Could you do that for your pending/incoming PRs?  Thanks!

**Comment by blakehawkins** [comment]
Looks good.

**Comment by thecoshman** [comment]
@david-mitchell you need to update this PR to resolve conflicts.

**Comment by hsutter** [comment]
Applied as a separate commit. Thanks!

**Pull request closed without merging**
