### PR TITLE
Added some example tooling discussion.

### PR DESCRIPTION
**Pull request by tituswinters**
For issue 529

### CODE REVIEW

**Comment by tkruse** [comment]
To fix travis failure, fix mentioned spelling mistakes / add new words to the dictionary at
https://github.com/isocpp/CppCoreGuidelines/blob/master/scripts/hunspell/isocpp.dic

from the travis report:
```
Line 11644: verisons -> versions
Line 11644: gcc -> GCC
Line 11652: Clang's -> Slang's
Line 11653: tsan -> tan
Line 11656: 10x -> 10s
Line 11656: 20x -> 20s
Line 11657: unittests -> unit tests
Line 11658: tsan -> tan
```

**Comment by tkruse** [comment]
Missed line 11657 "unittests"

**Comment by AndrewPardoe** [comment]
I added "unittest" to the dictionary.

**Comment by AndrewPardoe** [comment]
Per our editors' discussion, we think this discussion about tooling might be better in the Philosophy discussion. I've created Issue #840 for Bjarne to create this new item. Thank you for the starting text and suggestion, Titus!

**Pull request merged**
