### PR TITLE
Fix CI errors from bad brackets

### PR DESCRIPTION
**Pull request by JonasToth**
This is a attempt to fix the ci error currently existing. I think the `...` were the problem, and therefore i created a comment around them. If this does not fix the errors, i will remove the PR again.

### CODE REVIEW

**Comment by jwakely** [comment]
No, it tells you the problem:

> Res-if1.cpp:17:  Missing spaces around !=  [whitespace/operators] [3]

This is fixed by #1037

**Comment by JonasToth** [comment]
But #1037 did still fail.

I oversaw it sorry. Shall i fix the linelength error then or just leave it as it is?

**Comment by jwakely** [comment]
> But #1037 did still fail.

For a different reason, and nothing to do with `...`

**Comment by JonasToth** [comment]
Yes. Sorry for the noise.

**Pull request closed without merging**
