### PR TITLE
Update Example Section in hierarchies

### PR DESCRIPTION
**Pull request by AmeenAli**
add code example at rule (An abstract class typically doesn't need a constructor)

### CODE REVIEW

**Comment by AmeenAli** [comment]
@AndrewPardoe  will you merge this ?

**Comment by blakehawkins** [comment]
@AmeenAli I am not a repository owner but I will take a look and offer some feedback - inline comments to come.

**Comment by thecoshman** [comment]
This should have been authored as two commits as you are trying to update two independent sections of the guidelines.

I also fail to see what the two examples you have offered really do towards helping to understand the rules, if anything they seem to offer more confusion. Though I do think the 'reason' you offer for namespace, whilst not perfect, is better than nothing.

**Comment by AndrewPardoe** [comment]
Ameen, thank you for making these suggestions. The two "bug fix" commits have been added. The two editorial commits should be discussed as Issues first, based on the discussion here and private review.

**Pull request closed without merging**
