### PR TITLE
Fix issue #1026

### PR DESCRIPTION
**Pull request by tg-m**

### CODE REVIEW

**Comment by tg-m** [comment]
@jwakely It somehow generated new number, i.e., 1027. Sorry...

**Comment by jwakely** [comment]
Yes, that's how GitHub works - pull requests are distinct "issues" with their own number. If you want to submit a pull request then just do that, don't open an issue and then also a pull request to fix it.

Anyway I've merged the fix - thanks!

**Comment by tg-m** [comment]
OK. That's what I wanted to do initially, but then I've noticed that there is an issue about a typo (#1025 I guess), so I've made another one. Thanks for the info.

**Comment by jwakely** [comment]
1025 is a pull request, not an issue.

**Pull request merged**
