### PR TITLE
fix minor style issues

### PR DESCRIPTION
**Pull request by tkruse**

### CODE REVIEW

**Comment by thecoshman** [comment]
The changes as a whole look good, but it would be good, imo, if you could look to squash this all down to one commit for al this editing.

**Comment by tkruse** [comment]
I can squash no problem. It's unsquashing that's painful :-) , when one commit needs to be taken out / reverted.

All squashed.

**Comment by thecoshman** [comment]
I think given the content of these changes, it's handy enough to handle as a singular commit.

**Comment by tkruse** [comment]
squashed already

**Comment by gdr-at-ms** [comment]
There appears to be conflicts.

**Comment by tkruse** [comment]
rebased

**Comment by tkruse** [comment]
conflict was in line 5974
```
std::swap(a, b);   // propably not what we wanted: calls std::swap()
```
in case you want to review that line again, after I fixed conflict

**Comment by tkruse** [comment]
actually, I just see propably has typo

**Comment by tkruse** [comment]
typo fixed (propably -> probably)

**Pull request merged**
