### PR TITLE
Enforcement rule for I.3: Avoid singletons

### PR DESCRIPTION
**Pull request by Eliyahu-Ravuna**
Look for every class T where one of the static data members or static local variables is of type T, T* or T&.

### CODE REVIEW

**Comment by GregUtas** [comment]
Thanks, but I'll pass on any enforcement of this.
It's legitimate to limit the number of instances of something to 1, and to make that 1 easy to access. Flyweights, for example.  As in auto fly = Singleton<Flyweight>::Instance();
Singletons can be abused, but so can many things.  This rule needs exceptions.  Right now, the only one is the idiom for avoiding the static order initialization fiasco.

**Comment by GregUtas** [comment]
That should read auto fly = Singleton< Flyweight >::Instance().  [clueless as to how this isn't WYSIWYG]

**Comment by gdr-at-ms** [comment]
We thought about this suggestion, but concluded that it will have too many false positives.
We propose the following instead that if a class X has a public static function that contains a function-local  static of the class' type X and returns a pointer or reference to it, ban that.

**Comment by Eliyahu-Ravuna** [comment]
Sure. I have put the revised version under #374.

**Comment by drearyworlds** [comment]
I'm confused as to how this:

**X& myX()
{
    static X my_x {3};
    return my_x;
}**

is not the same as this:

 **•If a class X has a public static function that contains a function-local static of the class’ type X and returns a pointer or reference to it, ban that.**

Can someone help me understand? Not sure if this is recommended or not.

**Pull request closed without merging**
