### PR TITLE
Add virtual destructor to base class "Device"

### PR DESCRIPTION
**Pull request by brenoguim**
Add virtual destructor to interface class following recommendation of [C.127](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c127-a-class-with-a-virtual-function-should-have-a-virtual-or-protected-destructor).

### CODE REVIEW

**Comment by brenoguim** [comment]
Hm... There is still something fishy here.

[C.127](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c127-a-class-with-a-virtual-function-should-have-a-virtual-or-protected-destructor) specifies that one should use virtual destructor. That's fine, I did that.

But it doesn't say if one should use a pure virtual destructor or a defaulted virtual destructor.
It uses a pure virtual destructor, but I added a defaulted destructor on my pull request.

I'm not sure which is better, if any.

**Comment by jwakely** [comment]
There is no advantage to making it pure virtual, because the class is already abstract. Defaulted seems fine here.

**Comment by brenoguim** [comment]
Ok, cool!
Now let me just figure out why that change failed on the CI

**Comment by jwakely** [comment]
Just inspect at the test results:
````
Warning: Spellcheck failed, fix words or add to dictionary:
Line 11728: nodiscard -> no discard
Line 11728: nodiscard -> no discard
Line 11728: nodiscard -> no discard
Line 11740: nodiscard -> no discard
make: *** [hunspell-check] Error 1
````

This isn't caused by your change. I'll fix it.

**Comment by brenoguim** [comment]
Thanks!

**Comment by brenoguim** [comment]
I guess it is still failing due to this:

```
Rconc-task0.cpp:17:  Lines should be <= 100 characters long  [whitespace/line_length] [2]
Done processing Rconc-task0.cpp
Total errors found: 1
 14  // ../CppCoreGuidelines.md : 13401
 15  void some_fun() {
 16      std::string  msg, msg2;
 17      std::thread publisher([&] { msg = "Hello"; });       // bad (less expressive and more error-prone)
 18      auto pubtask = std::async([&] { msg2 = "Hello"; });  // OK
 19      // ...
 20      publisher.join();
 21  }
```

**Comment by brenoguim** [comment]
Created PR #1069 to fix the line length problem.

**Comment by AndrewPardoe** [comment]
Thank you for the change, and for maintaining it per our feedback.

**Pull request merged**
