### PR TITLE
ES.45/ES.46 renamed and reordered to match anchors found later in file

### PR DESCRIPTION
**Pull request by tlanc007**
In the TOC the ES.45 was tagged for narrowing and ES.46 was tagged for magic.  But later in the file where the anchors are given, they were swapped.  So I changed the Table of Contents to match the tags used later in the file.

If the preference is to keep ES.45 for narrowing and ES.46 for magic in the TOC.  I can put those back and fix up the usage later in the file instead.  I just went with the easier change.

### CODE REVIEW

**Comment by blakehawkins** [comment]
You've got a merge commit, suggest rebasing

**Comment by tlanc007** [comment]
Good point.  Looking into getting rid of it.

**Comment by tlanc007** [comment]
Ok, the merge commit is removed.

Before someone accepts this they should make sure renaming ES.45 and ES.46 is an acceptable action.  If there is a desire to keep the original order in the TOC, then the alternative is to fix the anchors in the document body.

**Comment by AndrewPardoe** [comment]
Thanks!

**Pull request merged**
