### PR TITLE
Added NL9 example

### PR DESCRIPTION
**Pull request by richelbilderbeek**
Did PR #184 cleanly from scratch.

### CODE REVIEW

**Comment by thecoshman** [comment]
You need to clean this up.

You still have merge details in this final version, and there should only need to be a single commit for a PR like this. Perhaps you should take the time now to read up on git :)

**Comment by richelbilderbeek** [comment]
Damn, I _deleted_ the older fork to get rid of those failed pull request squashes. Again sorry for the hassle, I will plan for some hours to do this properly...

**Comment by tkruse** [comment]
#184 could be manually closed as duplicate already.

**Comment by tkruse** [comment]
@gdr-at-ms, in case you did not know, PRs can easily be modified locally with this tip:
http://stackoverflow.com/questions/27567846/how-can-i-checkout-a-github-pull-request

Add this line to your .git/config:
```
fetch = +refs/pull/*/head:refs/remotes/origin/pr/*
```

Then git fetch will give you all PRs as branches, and you can squash/rebase/merge/push from local.
In some cases this will lead to less effort for you than multiple interactions trying to get a PR fixed.

**Pull request closed without merging**
