### PR TITLE
Added two examples to NL section

### PR DESCRIPTION
**Pull request by alrekr**
Created two examples for Names and Layout section.

### CODE REVIEW

**Comment by blakehawkins** [comment]
Looks good.

**Comment by thecoshman** [comment]
I think the rule regarding camel case should be expanded to show how it applies to names of variables, functions, types, etc. Thinking of languages like Java where there is a very set style of using block capitals for 'constants', 'CambelCase' for classes but 'camelCase' for variables.

**Comment by alrekr** [comment]
@thecoshman I think your suggestion is really covered by NL.8 (consistent naming style). There might be a clash with NL.10; I think you should open an issue for that.

Generally I don't read NL.10 as something that perceives variables, functions, types as different when it comes to camelcasing or not. Constants (e.g. defines, enums) are already written in capitals in the code I see, but that appears to be in conflict with NL.9. NL.8 shows how home made types should start with capital if one follows Stroustrup style. But above NL.9 and NL.10 is NL.8; just be consistent.

**Comment by thecoshman** [comment]
Huh, seems some of those links are broken... opened issue for it to be fixed up at some stage.

No, NL8 is about sticking to a consistent style. What I am referring to is the convention very common Java (and other languages of course) to have different styles for different 'types' of names. For example, a variable might always be 'done_like_this' whilst function names might be 'doneLikeThis'. It is two distinct styles for two distinct types of names. 

I think the issue here is that 'name' seems to be applying to everything that a programmer can provide a name for.

But yes, NL9 is very clear that block caps is exclusively for macros, and considering how much mess you can get into, I think it makes sense to reserve such visually offensive formating for them. There is nothing inherently special about constants or enums, other than the compile will slap you for trying to assign to them.

**Comment by alrekr** [comment]
@thecoshman That is a really good point. You're right; NL.8 really need to define what it applies to. Right now, all examples are concerning variables. 

I really think you should open an issue on this, so more people can get in on the discussion of whether variables_should_be_named_differently than HowWeShouldNameFunctions. I, for one, don't want to be one half of a discussion that might have a lasting impact on the Core Guidelines :-)

Personally I would vote for no caps and underscores, since I find that parentheses clearly shows when it's a function and when it's a variable.

**Comment by AndrewPardoe** [comment]
Per editor's discussion: merge this.

**Comment by AndrewPardoe** [comment]
Closing this as there are examples in NL.5 and 10 now.

**Pull request closed without merging**
