### PR TITLE
t.65: more fixes in the examples

### PR DESCRIPTION
**Pull request by akimd**
Sorry, there were other issues I had overlooked.

### CODE REVIEW

**Comment by AndrewPardoe** [comment]
Thank you for the suggestion! This code is either fine as it is, or we should use the Concept name. We shouldn't do something custom. I'll create an issue for this. 

Thanks for finding the bug!

**Comment by akimd** [comment]
I'm not sure I understand why the patch was not installed but the merge request closed.  The current document is still buggy in many regards, addressed by my changes.  Concepts can be an improvement, sure, but meanwhile, something correct seems useful.

BTW, elsewhere `typename` seems preferred to `class` for type parameters.  I stayed with `class` to be consistent with the original author, but that might have been the wrong choice.

**Comment by gdr-at-ms** [comment]
I think it was recognized that you found a genuine bug and that will be fixed.  However the abbreviation `IterIn` was not considered a good change.  The editors preferred either retaining the existing parameter name or use full concept names as has been the practice over the last two decades or so.

**Comment by akimd** [comment]
Hi Gabriel.  Thanks for the clarification.

In the rest of the document `Iter` is often used together with a `require` to specify the nature of `Iter`.  So I guess with could have `Iter1` which models the `Input_iterator` concept and `Iter2` for `Output_iterator`, but we probably should not use `InputIterator` and `OutputIterator` for the template parameters, as it really looks like the names of the concept.  Yet `Iter1` and `Iter2` are really not sexy.

FWIW, Andrew Sutton used `I` and `O` in his implementation (https://github.com/asutton/origin/blob/master/origin/algorithm/copy.hpp).

CppReference use `InputIt` and `OutputIt` (http://en.cppreference.com/w/cpp/algorithm/copy).

I thought I saw somewhere a draft of the C++ standard's section about the library updated with concepts, but cannot put the hand on it.  I would have liked to see the naming convention used there.

**Comment by maikel** [comment]
> I thought I saw somewhere a draft of the C++ standard's section about the library updated with concepts, but cannot put the hand on it. I would have liked to see the naming convention used there.

Do you mean?
http://open-std.org/JTC1/SC22/WG21/docs/papers/2016/n4569.pdf

Also worth a look: https://github.com/CaseyCarter/cmcstl2

**Comment by akimd** [comment]
@maikel Thanks.  I was nothing thinking about that precise documentation, I thought there was a companion draft to the report that adds concepts to the language that was about the changes in the library to support concepts.

In this document, Eric uses `I` and `O`.  However, note that the concepts are `InputIterator` and `OutputIterator`, not `Input_iterator` and `Output_iterator`.  Who is right?  See for example [alg.copy], p.154 (25.3.1).

```c++
template<InputIterator I, Sentinel<I> S, WeaklyIncrementable O>
  requires IndirectlyCopyable<I, O>()
  tagged_pair<tag::in(I), tag::out(O)>
    copy(I first, S last, O result);
```

**Pull request closed without merging**
