### PR TITLE
update Enumerations,divide by zero sections

### PR DESCRIPTION
**Pull request by AmeenAli**
Prefer enums over macros : update Reason and example sections
divide by zero : update example section

### CODE REVIEW

**Comment by blakehawkins** [comment]
I think you should squash your commits, or otherwise somehow improve their metadata.

**Comment by AmeenAli** [comment]
@blakehawkins @evol3m  im sorry i was trying to fix something and forgot to commit it to local branch instead of the master branch :(

**Comment by Cokemonkey11** [comment]
@AmeenAli no problem! You can fix this -

* Check out a new branch `git branch enumerations_and_div_zero`
* Force the master branch back to the real master: `git fetch upstream` `git pull -f upstream master`
* Squash your commits `git checkout enumerations_and_div_zero` `git rebase -i $(git merge-base master HEAD)` (set `pick`s to `squash` as desired)
* Rebase onto master: `git rebase master`

Then make a new pull request.

**Comment by blakehawkins** [comment]
@AmeenAli no problem! You can fix this -

* Check out a new branch `git checkout -b enumerations_and_div_zero`
* Force the master branch back to the real master: `git fetch upstream` `git branch -D master` `git checkout upstream/master` `git checkout -b master`
* Squash your commits `git checkout enumerations_and_div_zero` `git rebase -i $(git merge-base master HEAD)` (set `pick`s to `squash` as desired)
* Rebase onto master: `git rebase master`

Then make a new pull request.

**Comment by AndrewPardoe** [comment]
It looks like this has been rebased and can be merged.

@AmeenAli, please submit smaller PRs instead of adding different commits to one PR. It helps discussion and helps prevent merge issues. 

Assigned to gdr-at-ms for review.

**Comment by AmeenAli** [comment]
@AndrewPardoe what @blakehawkins  told me to do didn't work well .. i will close this PR and open another clean one.

**Pull request closed without merging**
