### PR TITLE
Delete two "???" rules about context switches.

### PR DESCRIPTION
**Pull request by Quuxplusone**
These rules have no examples, no rationale, no enforcement.
As such, I don't think they belong in the list of Guidelines.

### CODE REVIEW

**Comment by shaneasd** [comment]
It does seem like the only people who are going to properly understand this rule as written are people for whom it's already obvious.

**Comment by cubbimew** [comment]
the triple-question marks are basically "// TODO", and however the CPUs improve, this is still a notable hidden cost.

An direction to useful wording for CP.40 could be something like "avoid creating too many threads, prefer fixed-size thread pools instead" and for Per.30 perhaps pin critical thread to a dedicated core

**Comment by shaneasd** [comment]
But who benefits from having these rules here in their current form? The assertion made in this pull request (at the risk of putting words in Quuxplusone's mouth) is that the end user doesn't benefit. Yes they could be completed and then they would be good actionable advice but that's not the case currently. If the benefit is to the authors of the guidelines then wouldn't it be better to have these as an Issue in github. There appear to be plenty of examples of this.

Perhaps this is a placeholder for structural reasons (e.g. to ensure nothing else claims the index)?

**Comment by hsutter** [comment]
Editors call: We agree with the point that the rules shouldn't stay empty, but we also believe that they ought to be in the "C++ Core" Guidelines because C++ is about performance, this is often violated accidentally. We continue to plan to fill these in.

**Pull request closed without merging**
