### PR TITLE
Updated C.67 and C.130

### PR DESCRIPTION
**Pull request by akrzemi1**
This addresses https://github.com/isocpp/CppCoreGuidelines/issues/1246.

### CODE REVIEW

**Comment by cubbimew** [comment]
travis-ci errors:
two counts of  "Line ends in whitespace.  Consider deleting these extra spaces."
and three counts of "Spellcheck failed, fix words or add to dictionary:"
Line 6070: b2 -> b
Line 6070: 'B' -> B'S
Line 6093: inadvertant -> inadvertent

**Comment by akrzemi1** [comment]
Thanks for the report. I have fixed white spaces and "inadvertant". However b2 (name of a variable) and 'B' (quoted characters) are fine, and adding them to dictionary does not seem to make sense?

**Comment by cubbimew** [comment]
> adding them to dictionary does not seem to make sense?

The dictionary (https://github.com/isocpp/CppCoreGuidelines/blob/master/scripts/hunspell/isocpp.dic) has all sort of variable names and quoted characters in it. It could be improved, but as-is it's simpler to satisfy the check by updating that file.

**Comment by akrzemi1** [comment]
Ok, updated dictionary.

**Comment by hsutter** [comment]
Editors call: Looks good! We also want to make sure C.130 discourages copy assignment, but can edit that in post-merge.

**Pull request merged**
