### PR TITLE
Changed markdown syntax highlight

### PR DESCRIPTION
**Pull request by Voultapher**
Instead of 4 whitespaces used `cpp` around code blocks.
Using the cpp style flag enables syntax highlighting.

### CODE REVIEW

**Comment by Voultapher** [comment]
[This](https://gist.github.com/Voultapher/ec1840178c186827b52df3afeb308802) is the code used for changing the syntax.

**Comment by hsutter** [comment]
Note that [Travis checks fail](https://travis-ci.org/isocpp/CppCoreGuidelines/builds/168660130) with 700+ of the same error saying. Here's the first:

>   `275:1-277:105      warning  Missing blank line before block node  no-missing-blank-lines`

(I'm not saying the PR would be merged if this was fixed, just pointing out a mechanical issue.)

**Comment by Voultapher** [comment]
What is a block node?

**Comment by congdanhqx** [comment]
@Voultapher 
> 275:1-277:105      warning  Missing blank line before block node  no-missing-blank-lines

In line 275 (and other lines), it's necessary to insert a blank line after ```

**Comment by Voultapher** [comment]
Can someone please run the tests again to if it fixed the node block problem

**Comment by tkruse** [comment]
See #328, #96, #33 . Maybe it would be good to leave a syntax highlighting PR open, just so that nobody else goes through the trouble of creating yet another such PR.

**Comment by Voultapher** [comment]
**Compromise**: Have a script that builds a highlighted version of the guidelines. Best of 2 worlds, make the non-highlight the default and link the willing to the highlighted version.

Same benefits of not the current solution and people such as those reading the document on github can enjoy the objectively more pleasant to read version if they want.

**Comment by tkruse** [comment]
I helped creating a github page that has a button to switch on/off highlighting, see http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines and see the gh-pages branch.

And while your python isn't bad (much better than my scripts), using remark is much safer to create fenced code blocks.
See https://github.com/wooorm/remark

E.g. see "check-markdown" in https://github.com/isocpp/CppCoreGuidelines/blob/master/scripts/Makefile


One general issue is that not every literal block in the document is necessarily a cpp code snippet, so from this point of view it would make a little more sense to make highlighting the default, and non-highlighting the derivative with loss of information.

Travis would allow for automatic commits, so in theory it would be possible to create a different github branch that automatically has new commits when the master branch has a new commit. That could be used for highlighting or even for pushing PDFs to github (Recipes exist to use pandoc, latex and docker to create PDFs). However, at the end of the day, there is nobody to maintain any such added tooling / infrastructure.

**Comment by AndrewPardoe** [comment]
I'm updating the contributing.MD to note discussions that we have already had.

**Comment by galik** [comment]
**FWIW** For a while I have been maintaining a syntax highlighted version of the guidelines with an automated update script that synchronizes with the main repository every 6 hours.

https://github.com/galik/CppCoreGuidelines/blob/syntax-highlights/CppCoreGuidelinesSH.md

The code to convert the Markdown is here:

https://github.com/galik/CppCoreGuidelines/blob/syntax-highlights/contrib/add-github-syntax-highlights.cpp

Some may prefer this as the highlighted code in the `gh-pages` version does not seem to be particularly colorful or highlighted.

**Comment by tkruse** [comment]
Just making sure... the gh-pages version requires enabled javascript and the user to click the "highlighting" button, which is "hidden" in the sidebar.

And with some more hacking, any of the highlight.js schemes should be possible:
https://highlightjs.org/static/demo/

In https://github.com/isocpp/CppCoreGuidelines/blob/gh-pages/_includes/head.html
I included the github.min.css, which I assumed would be close to github (no other reason for my choice). I think nobody would complain much about switching to a more colourful highlighting.

**Pull request closed without merging**
