### PR TITLE
Add Fenced code blocks with syntax highlighting

### PR DESCRIPTION
**Pull request by Liryna**
The syntax highlighting will help the reader to review the code examples.

### CODE REVIEW

**Comment by Liryna** [comment]
I have rebase with the last changes

**Comment by AndrewPardoe** [comment]
Liryna, thanks for doing this work. Please see the discussion in Issue #33. We'll wait on this PR until that gets resolved.

**Comment by galik** [comment]
It seems to me that the difficult work is the change to *fenced code blocks*. If that is done then writing a tool to add the *syntax highlighting* would be trivial for those that want it (its less portable).

**Comment by Liryna** [comment]
@galik, this is already done in my PR :smiley:

**Comment by galik** [comment]
@Liryna I pulled your version because I like the syntax highlighting. Unfortunately it doesn't work with the Markdown tools I use. So I thought it might be good just to commit a version with *fenced code blocks* (your PR without the syntax colouring) for the main repo and then people can easily add the syntax colouring if they need it.

**Comment by AndrewPardoe** [comment]
@Liryna, thank you for the suggestion. We prefer to have simple code examples for the time being.

**Pull request closed without merging**
