### PR TITLE
Markdown lint, cpp lint and spelling fixes

### PR DESCRIPTION
**Pull request by jacobl-at-ms**
This cleans up a number of minor build issues.

The only issue I see remaining after this is:
14013:15-14013:58  warning  Don’t pad `emphasis` with inner spaces               no-inline-padding
14014:21-14014:45  warning  Don’t pad `emphasis` with inner spaces               no-inline-padding

These appear to be unresolvable with the current version of remark.  Very similar lines are on 14032-33 and don't generate these errors.  Moving the reported lines there results in no break.  Moving the lines at 14032-33 to 14013 results in them having the same issue.  If you just put the header blocks around the inline code block as in 14030-35 then the issue also goes away.

Haven't had a chance to investigate if a newer version of remark would fix the issue.

### CODE REVIEW

**Comment by jwakely** [comment]
Oh, I noticed some of these typo fixes and made the same changes myself earlier today. Thanks for addressing some more of them.

**Comment by tkruse** [comment]
Possible solutions/workarounds for the last remaining issues:

- indent code block by 2 additional blanks
- indent *all* bullet point contents by 2 additional blanks, and enable that remark rule to enforce it
- Add a text line between the bullet and the code block:
Like this
```
* Bullet
Example code:
   
    code

```

Note:
Not sure if any version of remark would ever be able to parse the current text without change. The general problem being that 2 additional indents are the canonical way to embed more lines within bullet points. Without that, the parser has to heuristically guess the intention, with caveats such as code blocks not being recognized. So it might not be a remark bug, just a caveat for people who refuse the 2-blank indent inside bullets.

**Comment by jacobl-at-ms** [comment]
I took the extra line of text between bullets and code block since it seemed the least intrusive and now travis looks clean again.

**Comment by AndrewPardoe** [comment]
closing per #867

**Pull request closed without merging**
