### PR TITLE
Avoid `std::endl` :)

### PR DESCRIPTION
**Pull request by Cleroth**

### CODE REVIEW

**Comment by LeftofZen** [comment]
+1
https://github.com/isocpp/CppCoreGuidelines/issues/357

**Comment by jwakely** [comment]
The reason to avoid `endl` is because the flush is not usually needed. If the flush _is_ wanted, then using `endl` is appropriate. This doesn't look like an improvement to me.

**Comment by jwakely** [comment]
Since `cerr` is unbuffered by default the flush doesn't do anything. So I would suggest either this should use `'\n'` and not flush, or should continue to use `endl` (to handle the unlikely case where somebody has changed `cerr` to be buffered, but I doubt the author of this example was thinking of that case).

**Comment by Cleroth** [comment]
`endl` is often just used everywhere though, rather than when a flush is needed, hence why the rule is there to avoid using `endl` because it doesn't really make your intention clear. The fact that this piece of code used `endl` when cerr is unbuffered just goes to show that `endl` is misused very often.

**Comment by gdr-at-ms** [comment]
@jwakely  is right.
I am a bit surprised by the intense focus on `std::endl` in recent days.  I don't see any of the various proposals as actually improving on the situation.

**Comment by jwakely** [comment]
Then the fix should not include the `flush`.

**Comment by Cleroth** [comment]
Like you said cerr can be redirected though. Either way I've removed the `std::flush`. I don't particularly care, and I think the 'avoiding std::endl' shouldn't even be in here as it's an insanely minor thing, I only commited it because the guidelines state to avoid it while still doing it.

**Comment by agauniyal** [comment]
People say _'avoid std::endl'_ because beginners (and sometimes non-beginners as well) tend to overuse `std::endl` at places where a simple `'\n'` would have been sufficient. `std::endl` sounds like _End Line_ to me and not _End Line and Flush Please_, plus the fact some other languages don't necessarily flush with their print line functions and people usually assume same here, make this much worse. That's the reason why people aren't saying - _'avoid std::flush'_!

**Comment by MikeGitb** [comment]
@agauniyal: Thanks for the explanation.

First of all, I don't think the core guidelines are a good fit for completive programming/will be adopted for those tasks anyway. Many programs In see there do far worse things than using printf.

Second, the (now closed) issue about this topic proposed to ban std::endl outright - not just to avoid it.

Third, even using `\n` it is quite likely that cout will still be slower than printf, unless `sync_with_stdio(false)` is called.

Finally, the PR at hand wants to remove the std::endl just before an std::exit. If there ever is a situation, where I want an output steam to be flushed it is for sure before that program gets terminated.

I'm completely fine with a guideline cautioning against using endl when it is not needed and explaining the reason behind it, but people shouldn't get zealous about it

**Comment by neilmacintosh** [comment]
Looks perfectly reasonable to us.

**Pull request merged**
