### PR TITLE
Fix typos in section C: Classes and class hierarchies

### PR DESCRIPTION
**Pull request by severinmeyer**
This branch fixes several typos in the regular text of the C section. Code is not affected.

CONTRIBUTING.md states that:
"_If you are making many small changes, please create separate PRs to minimize merge issues._"

However, it seems a bit excessive to open 11 pull requests. As a compromise, I have created a separate commit for each typo, and offer them here as a branch.

If you prefer another form, let me know.

### CODE REVIEW

**Comment by blakehawkins** [comment]
All looks good to me.

**Comment by AndrewPardoe** [comment]
No problem at all with the single PR. The note is more meant for people who want to do huge refactorings. Typos are easy! Thank you!

**Comment by severinmeyer** [comment]
That is good to know, thank you.

Now, I have lined up 28 more typo fixes for 5 other sections. But I noticed that the approach of the individual commit per typo still somewhat inflates the log.

Would you prefer if I pushed a single commit for all typos within a section?

And should I continue to open a pull request per section, or should I combine them into a single request?

**Comment by Cokemonkey11** [comment]
I suggest just using your preferred workflow in this case. Viewing all the commits together isn't a problem as you can just unify them - see here for example:

https://github.com/isocpp/CppCoreGuidelines/pull/796/files

image

**Comment by severinmeyer** [comment]
Cokemonkey11, thank you for your input.

But I should clarify my concern. I noticed that if I commit each typo fix individually, Github will [list][1] me as one of the top contributors with 42 commits. I think we can all agree that that would not be justified.

So I wonder if it is OK to squash the commits.

[1]: http://github.com/isocpp/CppCoreGuidelines/graphs/contributors

**Comment by severinmeyer** [comment]
I'm still new to Github, so I'm probably making this far more complicated than necessary. I will go ahead and simply squash the commits per section and open respective pull requests. Thank you for your assistance.

**Pull request merged**
