### PR TITLE
Clarify f.6 note on noexcept and allocation

### PR DESCRIPTION
**Pull request by tituswinters**
The bigger picture issue of "What context is your code executing in?"
and "What type of code are the core guidelines addressing?" should be
handled separately with text in the overview.

(This was discussed further in https://github.com/isocpp/CppCoreGuidelines/issues/421)

### CODE REVIEW

**Comment by cubbimew** [comment]
Is this a Java programming guideline? If my code executed std::vector<int> v(-1, 0);, I'd like to roll back to the scope where that -1 originated from.

**Comment by cubbimew** [comment]
I disagree with "majority of programs and execution environments cannot meaningfully handle a failure to allocate".

`std::bad_alloc` from `std::vector<int> v(-1, 0);` indicates an error with the same meaning as  `std::out_of_range` from `v.at(-1);` - if a program handles errors at all, it can handle that one meaningfully.

As for the situations where the allocation request is provably correct, but fails due to resource constraints, there are many meaningful ways in which existing applications handle that without aborting. Choosing another algorithm (a-la std::inplace_merge), lowering heap usage by shrinking caches, or rejecting the service or user request that could not be completed and proceeding with the next one. 

The effect of placing `noexcept` on functions that may throw is better served by compiling with `-fno-exceptions` - as a build option rather than hard-coded policy.

**Comment by tituswinters** [comment]
The std::vector example is a red herring - one totally bogus constructor invocation that indicates a clear programmer error is not a good reason to change *guidance*, especially when that error is rare and easy/obvious to fix.

The argument is still that the majority of allocation failures *cannot* be handled at runtime.  Few applications have caches to flush as you suggest.  Few services are going to recover from one bad allocation by failing a request and then proceed on to be successful at the next.  Cluttering up *every* call to new or make_unique with attempted error handling is a mistake - in almost all cases the program is going to die at any moment anyway, it's better to gain a small percentage of performance in all other cases and die when it's time to die.

I'm not a decider on this, so the following may not matter.  However, you can convince me that this is wrong by surveying existing code, programs, projects and giving a real estimate of what fraction of those are well served by catching a bad_alloc from a genuine allocation.  It is of course possible that my estimate of what is common is off.  However, in practice, that seems ... unlikely.

**Comment by hsutter** [comment]
Thanks!

**Comment by cubbimew** [comment]
> one totally bogus constructor invocation that indicates a clear programmer error is not a good reason to change guidance,

At the time, the guidance didn't describe termination as the "cleanest and simplest" handling of an erroneous allocation request. Yes, much of bugtraq are clear programmer errors.

> Cluttering up every call to new or make_unique with attempted error handling is a mistake

This mistake is exactly what exception handling prevents. I certainly agree that bad_alloc cannot be handled locally in any non-contrived case I could think of.

> you can convince me that this is wrong by surveying existing code, programs, projects

My professional experience, where process termination on bad_alloc was never acceptable, involved telecom, city infrastructure, and finance, so that code is not readily accessible, however Photoshop from your first post in #421 was a great example of a common household application that people can identify with. It is surprising to read that applications taking user input are "rare". A quick look around similar themes in open source shows that LibreOffice, for example, handles bad_alloc for similar reasons in many places. Network servers are another obvious example that you keep rejecting -- which ones actually crash on large requests? Databases as well - ScyllaDB was the first to come to mind, and I see that they respond to bad_alloc by rolling back the request and not crashing the server (except if it happens to be in future::then -- they have an open issue to figure out what to do with that one abort)
 
But in any case, the editors made their choice.

**Comment by sehe** [comment]
@cubbimew 

> Databases as well - ScyllaDB was the first to come to mind, and I see that they respond to bad_alloc by rolling back the request and not crashing the server

Wouldn't it be a lot fairer to say they respond to bad_alloc by **attempting** to roll back the request. Unless things have been very meticulously designed to work without any allocation, chances are this doesn't work (and the server will rollback from a persisted transaction journal on restart, for a typical database type application).

This would seem to be the gist of the guideline: in general it's misguided to think you can safely do any work after suffering an un-categorized allocation failure. 

Of course you can be a lot more specific for targeted locations (such as the Photoshop example. This type of application makes _large_ allocations at specific times, and handling them specifically makes sense. But that directly contradicts the whole motion against you claim "I certainly agree that bad_alloc cannot be handled locally in any non-contrived case I could think of.")

**Comment by cubbimew** [comment]
Taking a brief look at https://codesearch.debian.net/  (nice tool by the way) "catch.*bad_alloc" gives 3625 hits in 315 packages and in the first dozen or so packages I checked there had many of the scenarios I brought up: user input handling (image loading in calligra and imagevis3d, large clipboard paste in fceux), large network input handling (xorp), failover to a slower algorithm a-la STL (calligra), a couple custom allocators and a whole lot of cleanup-and-rethrow and log-and-exit handlers.

Regardless of how well tested their bad_alloc handling is, it does not appear to be misguided, although I will admit that the "majority" claim made by this PR appears to be correct overall. I wonder how it holds up when libraries and utility apps with short life cycles are excluded.. I'll raise a new issue if I have an interesting result.

**Pull request merged**
