### PR TITLE
Reword how C11 Annex K functions are described

### LINKED ISSUE #1491: Incorrect statement in SL.io.3
Re this text:

> In C11, they are replaced by `gets_s()`, `scanf_s()`, and `printf_s()` as safer alternatives, but they are still not type safe.

@jwakely pointed out that: "This statement isn't true at all. The "safer" alternatives are optional in C11 and not widely supported, they don't replace anything. And I'm not sure what's wrong with printf() using %s, does it mean sprintf?"

@cubbimew added: "... printf_s would check if a null pointer is passed to %s (and also disable %n, which is a real security hazard)"

### PR DESCRIPTION
**Pull request by jwakely**
Fixes #1491

### CODE REVIEW

**Comment by cubbimew** [comment]
> Fixes #126

Did you mean "Fixes #1491"?

**Comment by jwakely** [comment]
I certainly did. I think I looked at this and thought it was the issue number:

Screenshot_20190815_161325

:man_facepalming:

**Comment by jwakely** [comment]
The commit log and this P/R are fixed now - thanks!

**Comment by hsutter** [comment]
Editors call: Thanks!

**Pull request merged**
