### PR TITLE
Issue #624 ES.34 Add Example.

### PR DESCRIPTION
**Pull request by GlassAndOneHalf**
This PR adds an example for ES.34

### CODE REVIEW

**Comment by MikeGitb** [comment]
In my experience, variadic arguments are rarely used in cases, where they can be replaced by a container that stores elements of a single type. Maybe you could also add an example, where a variadic function is replaced by a variadic template.

**Comment by GlassAndOneHalf** [comment]
Yes, I agree it's probably a good idea to include an example that is more closely related to the C-style varargs. I've added a new example to demonstrate the use of variadic templates in addition to the container example.

**Comment by AndrewPardoe** [comment]
Per our editor's discussion, the idea put forth in this PR is a good one. Unfortunately, ES.34 has an example using templates now. 

Would you rewrite this example using templates in the style of the example there now? Also, please use `constexpr` to get rid of the recursion.

**Comment by GlassAndOneHalf** [comment]
Working on this now.

**Comment by GlassAndOneHalf** [comment]
This should be complete. I'm not too sure if the build failure is being caused by my change?

**Comment by MikeGitb** [comment]
I'm not sure if this is important for the guideline at hand, but that function can (and imho should) be written non-recurssively. 
E.g. in c++11:

    template<class ... Args>
    void error2(int severity, const Args& ... args) {
        int t[] = {(std::cout << args, 0 ) ...};
        (void)t;
        std::cout << std::endl;
        std::exit(severity);
    }

or in c++17:

    template<class ... Args>
    void error1(int severity, const Args& ... args) {
        (std::cout << ... << args);
        std::cout << std::endl;
        std::exit(severity);
    }

**Comment by GlassAndOneHalf** [comment]
As @AndrewPardoe mentioned, as the function is `constexpr` the fact that the function is recursive shouldn't be any major concern.

However, having said that both of the examples you provided are much shorter. If we wanted to eliminate the recursive call, I would choose the C++17 example. The C++11 example is, imo, hard to understand - I have never seen that syntax before.

**Comment by MikeGitb** [comment]
@GlassAndOneHalf: Sorry, but I seem to be missing some important context here, because I understand neither @AndrewPardoe's nor your statement:

- As of 03dc7d3 the example in ES.34 doesn't have any templates
- I don't see what constexpr has to do with recursion here
- I'm pretty sure no function that does I/O can be constexpr anyway

Regarding the c++11 syntax: I'm pretty sure we already had a different PR or issue here, where this syntax was shown / discussed. I think I first saw it on SO a couple of years ago. 
I agree that the c++17 syntax is definitively preferable, but unfortunately not always applicable (and not yet widely available to the users). I wonder if the c++11 syntax should be discussed in a separate rule - like "Avoid variadic template recursion".

**Comment by cubbimew** [comment]
constexpr may have referred to if constexpr, which is another way to process variadic templates non-recursively. 
@MikeGitb  "Avoid variadic template recursion" is in fact a pending rule, see #749

**Pull request merged**
