### PR TITLE
Start the translation of the document to Russian

### PR DESCRIPTION
**Pull request by neshkeev**
In order to let Russian C++ developers have access to the Guidelines
this translation has been started.

### CODE REVIEW

**Comment by ruslangaripov** [comment]
I believe Russian C++ developers do have access to the Guidelines  :stuck_out_tongue_closed_eyes: I mean, do we really need this? :smiling_imp:

**Comment by Pazns** [comment]
The Guidelines seem to be in a fast moving pace, are you sure a translation would stay reliable over time ?

**Comment by neshkeev** [comment]
I started doing the translation for myself and then I realized that it might be helpful for someone else. But you are right, we need to wait for a milestone.

**Comment by Pazns** [comment]
I don't know if milestones are scheduled at all, on the other hand.
This is a pertinent issue.

**Comment by masterl** [comment]
Well, I'll start doing the translation in my own fork.
When a solution for this is decided, I can change the files to conform to it.

**Comment by Pazns** [comment]
@neshkeev 
Please consider Bjarne view : #684 .

**Pull request closed without merging**
