### PR TITLE
Removed useless "Currently (July 2016)"

### PR DESCRIPTION
**Pull request by arteniioleg**

### CODE REVIEW

**Comment by blakehawkins** [comment]
Are concepts not supported in GCC 7/8?

**Comment by jwakely** [comment]
> Are concepts not supported in GCC 7/8?

They are, so this pull request changes it from something that was correct in July 2016, and is now outdated, into something that is just blatantly wrong.

To remove the "July 2016" references to GCC 6.1 should be changed to something like "GCC 6 and later".

**Comment by arteniioleg** [comment]
Please provide the exact phrase that should be there or I will close this pull request and you do the changes.

**Comment by slx7R4GDZM** [comment]
Maybe have it say: "Concepts are supported only in GCC 6 and later."

**Comment by arteniioleg** [comment]
Updated

**Comment by cubbimew** [comment]
And now these will become outdated as soon as MS, Clang, and others catch up with at least the C++20 WP Concepts (if not the TS).

**Pull request merged**
