### PR TITLE
as pointed out at CppCon, 'inkorrekt and incompleat' doesn't translate

### PR DESCRIPTION
**Pull request by cubbimew**
In the Bjarne's keynote Q&A session, it was pointed out that "inkorrekt and incompleat" at the start of Core Guidelines was a blocker for adoption somewhere because the joke did not translate well.

### CODE REVIEW

**Comment by MikeGitb** [comment]
I saw that on YouTube, but didn't actually understand, what the problem was. Did they consider the document of poor quality, because it contained "typos"?

**Comment by JonasToth** [comment]
"inkorrekt" is an actual german word (meaning incorrect). 
the cryptic signs sometimes exist when porting german (ä,ö,ü,ß) into ascii, which is again a common thing germans see and judge as bad quality.
Germans don't get that kind of humor very well, too ;)

**Comment by jwakely** [comment]
*sigh* I wish this wasn't necessary. Isn't the poorly formatted "poorly formatted" text a big enough clue?

Just because some people miss the joke doesn't mean it must be removed. It's not offensive or hurting anybody.

**Comment by AndrewPardoe** [comment]
This line is pulled directly from the draft Standard: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4687.pdf. If the joke is acceptable there, it should be acceptable here.

**Comment by galik** [comment]
>"This line is pulled directly from the draft Standard..."

It's good to know that some jokes are being standardized. We wouldn't want them to get too funny too soon.

**Comment by AndrewPardoe** [comment]
We will remove the Unicode characters and replace the "bad formatting" with random bits of italics and bold. Also, the misspelling of "incomplet" should be fixed.

**Comment by jwakely** [comment]
> In the Bjarne's keynote Q&A session, it was pointed out that "inkorrekt and incompleat" at the start of Core Guidelines was a blocker for adoption somewhere because the joke did not translate well.

N.B. in the IS and TS draft it's incomplet not incompleat. We should get the joke right :)

**Comment by MikeGitb** [comment]
> "inkorrekt" is an actual german word (meaning incorrect).
the cryptic signs sometimes exist when porting german (ä,ö,ü,ß) into ascii, which is again a common thing germans see and judge as bad quality.
Germans don't get that kind of humor very well, too ;)

I happen to be German and found the joke quite obvious (unless there are some subtleties I'm oblivious to) and would vote for keeping it. On the other hand, if someone found it problematic enough to speak up at a conference about it, some action might be in order.

**Comment by jwakely** [comment]
I've adjusted the text to match what's in the working drafts of the C++ standard, including replacing the non-ASCII characters with some (valid) markdown formatting. Hopefully it's a bit more obvious now.

**Comment by JonasToth** [comment]
@MikeGitb yes me too, just wanted to explain it a little bit. But i certainly know some people i would suspect of getting it wrong, too :D 
The state now is better and even if some germans complain, shouldn't be changed again :)

**Pull request closed without merging**
