### PR TITLE
Add monospace tags around `using` keyword

### PR DESCRIPTION
**Pull request by free5lot**
Add monospace tags around `using` keyword in a couple of places.

### CODE REVIEW

**Review by jwakely — CHANGES_REQUESTED** [review]
This is wrong. The term "using declaration" is the formal name for one of the language features that uses the `using` keyword. It's not a "`using` declaration".

**Comment by free5lot** [comment]
> This is wrong. The term "using declaration" is the formal name for one of the language features that uses the `using` keyword. It's not a "`using` declaration".

1) I considered this too. Then I checked other cases in text. "Using declaration" is used as `using` declaration on Line 17760: _* Flag use of `typename` as a disambiguator outside `using` declarations_.
So at least it's about consistency. One of cases should be changed to make document more consistent.

2) Also "using declaration" is misleading, compare: 
> using using declaration 

and 

> using `using` declaration 

The second is better.

=> To my opinion `using` declaration is better, more consistent and readable.

**Comment by free5lot** [comment]
P.S. The auto-check is broken, isn't it? The PR is not breaking anything obviously but check fails for other reasons. Should it be posted as an issue in the tracker?

**Comment by free5lot** [comment]
I'm not a native speaker and maybe @jwakely is right that `using declaration` is fine like it is, but I doubt it.

Anyway, I stumbled on  _`without a using  something`_ because it initially looked like poor English. But in a second you understand what the author means (declaration of `using`). So I decided to make that place clean, clear and consistent with the other usage of _`using` declaration_ in the same text.

**Comment by free5lot** [comment]
OK, if you think current text does not need changes I'm fine with that.

**Pull request closed without merging**
