### PR TITLE
Suggest to use #pragma once as include guard when compiler supports it.

### PR DESCRIPTION
**Pull request by michihenning**

### CODE REVIEW

**Comment by jaredgrubb** [comment]
I believe one of the guiding principles of the Guidelines is that depend on _standard_ C++, and sadly pragma-once is not standard (yet?!)

**Comment by michihenning** [comment]
Yes, it's not standard, which is why I added the qualifier about compilers. But the compilers a lot of people care about (gcc, clang, Visual C++) support it, and it's a much less error-prone way to deal with double includes.

**Comment by jdgarciauc3m** [comment]
I think that #pragma once is a path for writing non-standard code.

In any case, using non-standard extensions should not be part from the "core" guidelines.

**Comment by michihenning** [comment]
Well, I don't know whether the aim here is purity or pragmatism. Pragmatically, it works for the vast majority of C++ projects. I would have thought that C++ developers would be smart enough to decide for themselves whether they want to use a non-standard #pragma or not. Seeing that most compilers that matter support it, it also appears pretty much irrelevant whether the feature is standard or not, because it is de-facto standard. But I'm not hung up about it, feel free to reject.

**Comment by igetgames** [comment]
I agree that the Core Guidelines should not encourage the practice of writing nonstandard code. Adherents are free to deviate as these are guidelines and can be taken piecemeal (or none at all). I think that de facto standards, including "#pragma once", can be thought of as style preferences. Preferred style shouldn't conflict with the guidelines, not invalidate them. 

FWIW, I use "#pragma once" on a proprietary project across two of those major compilers - it reads much better than include guards (and provides better build times).

**Comment by galik** [comment]
I like the idea that the guidlines only deal with standard, and therefore portable code. Maybe there is a case for someone with a say in the standards to recommend a standard alternative to *include guards* similar to the *pragma*? Something like `#header`?

**Comment by gdr-at-ms** [comment]
We don't consider `#pragma`s as part of the "good C++" styles that we want to encourage and promote.

**Comment by gdr-at-ms** [comment]
@galik See the work going on modules, and my CppCon 2015 talk.

**Pull request closed without merging**
