### PR TITLE
Prefer bullet points to a long sentence in SL section

### PR DESCRIPTION
**Pull request by honggyukim**
It'd be better to have bullet points than writing the points in a long
sentence even with description in parenthesis.

### CODE REVIEW

**Comment by honggyukim** [comment]
Hi, I just found something tiny but less readable so submitted this PR. Please take a look. Thanks!

**Comment by jwakely** [comment]
Thanks for the patch.

I'd prefer it to say "the following advantages" instead of "the below advantages".

You no longer have a grammatical sentence. Either each bullet point should be a complete sentence (start with capital letter and end with period) or there should be a period after the last bullet point, and maybe end the first and second bullets with a semi-colon.

**Comment by honggyukim** [comment]
I just updated it following your suggestions. Thanks so much for the review.

**Comment by honggyukim** [comment]
Thanks for your help :)

**Comment by hsutter** [comment]
Thank you!

**Pull request merged**
