### PR TITLE
CP.110 & CP.111: Double-checked locking

### PR DESCRIPTION
**Pull request by Eliyahu-Ravuna**
CP.110 renamed as "Do not write your own double-checked locking".
Explanation and two examples added.

### CODE REVIEW

**Comment by MikeGitb** [comment]
Just as a comment: I'm not an expert on this, but IIRC there are other usecases for double-checked locking than just threadsafe initialization (Fedor talks about this towards the end of this talk at [cppcon 2015](https://www.youtube.com/watch?v=1obZeHnAwz4)). So thread safe statics or `std::once_flag` might not always be the solution. 

Whether those cases are relevant for the wider audience I cannot say.

**Comment by Eliyahu-Ravuna** [comment]
Hi Mike, You are right. Double-checked locking may be very useful in lock-free programming. I added this case as an exception, but with a disclaimer: "**See the rule CP.100: Don't use lock-free programming unless you absolutely have to**".

**Comment by Eliyahu-Ravuna** [comment]
I squashed the original commit with the one that incorporates Mike's feedbacks.

**Comment by MikeGitb** [comment]
Another thought: Maybe this should be two distinct rules:
- Don't use double checked locking for threadsafe initialization 
- If you really need double-checked locking use a conventional pattern

**Comment by Eliyahu-Ravuna** [comment]
It looks much better when they are two distinct rules.
Commits squashed.

**Comment by AndrewPardoe** [comment]
Thank you! We like this content. 

In future, please don't change the anchors. We merged this PR to get the content and will fix the anchors by hand.

**Pull request merged**
