### PR TITLE
Remove irrelevant source file mistakenly committed.

### PR DESCRIPTION
**Pull request by michaelbprice**

### CODE REVIEW

**Comment by michaelbprice** [comment]
This should fix issue #1884 1884

**Review by jwakely — APPROVED** [review]

**Comment by michaelbprice** [comment]
Might someone with write access be able to merge this?

**Comment by cubbimew** [comment]
> Might someone with write access be able to merge this?

yes, but if it waits three more days (to next editors call) we get to find out whether its provenance is indeed questionable.

**Comment by michaelbprice** [comment]
> > Might someone with write access be able to merge this?
> 
> yes, but if it waits three more days (to next editors call) we get to find out whether its provenance is indeed questionable.

:+1:

**Pull request merged**
