### PR TITLE
Fixed minor typo in section P.2.

### PR DESCRIPTION
**Pull request by drusk**

### CODE REVIEW

**Comment by gdr-at-ms** [comment]
The PR appears to have conflicts.  Could you resolve them please.

**Comment by drusk** [comment]
It looks like there was some reformatting done after my PR which caused the conflict.  Currently it is up to date.

**Comment by blakehawkins** [comment]
Suggest squashing your commits.

**Comment by thecoshman** [comment]
This now looks good to go.

**Pull request merged**
