### PR TITLE
Editing P.9: "Don't waste time or space" Example Text

### PR DESCRIPTION
**Pull request by playmer**
Hi there, this example came up in a discussion with a newer coder in an #include channel. We explained what was going on with it and had a little talk about how it didn't seem helpful not to just explain it. Thus this PR was born.

### CODE REVIEW

**Comment by playmer** [comment]
Seems like the build failed due to it detecting `toLower` being "misspelled" by my reading. But let me know if there's something I can do to fix that.

**Comment by jwakely** [comment]
See `scripts/hunspell/isocpp.dic` for the custom dictionary.

**Comment by playmer** [comment]
Okay, added it to the dictionary. Looks like it passed! Thanks for the tip off on that!

**Comment by hsutter** [comment]
Editors call: Merged, thank you!

**Pull request merged**
