### PR TITLE
Declaring one name per declaration.

### PR DESCRIPTION
**Pull request by dkorolev**

### CODE REVIEW

**Comment by Pazns** [comment]
What is the purpose of your commit 6a39167 on line 7883 ?
Is this recommended by current guidelines ?

**Comment by dkorolev** [comment]
Yes. https://github.com/isocpp/CppCoreGuidelines/blob/6a39167b8661ab5f2dcfd0a78a4d3800785b3f58/CppCoreGuidelines.md#Res-name-one

**Comment by Pazns** [comment]
Thanks for the note.

**Comment by blakehawkins** [comment]
Looks good.

**Comment by AndrewPardoe** [comment]
Thank you!

**Pull request merged**
