### PR TITLE
update Enumerations,divide by zero sections

### PR DESCRIPTION
**Pull request by AmeenAli**
this is a new clean PR based on my old dirty one :p

### CODE REVIEW

**Comment by thecoshman** [comment]
"this is a new clean PR based on my old dirty one :p" should not be in the commit message.

**Comment by thecoshman** [comment]
The expanded explanation for use of enums is not very easy to follow. The example is also especially confusing, as you don't use an enum, just a const.

The example of divide by zero could use further annotation to explain what exactly is going on and what is wrong. Perhaps also show how to avoid the issue. One the key points Bjarne made was that it's not good enough to simply say things are bad, you have to show how to do it good.

**Comment by avakar** [comment]
Also, what's up with spaces before commas?

**Comment by hsutter** [comment]
Thanks! I've applied the suggestions as 10d1d9d instead of merging this PR.

Note that this is two different suggestions in a single PR (please use one PR per item):
* Added descriptive text about use of enums vs macros in debugging. I've tightened it up and added it.
* Added a potential divide-by-zero example. This could be helpful if it also showed what to write instead, so I added two alternatives.

**Pull request closed without merging**
