### PR TITLE
the main() function should return an int

### PR DESCRIPTION
**Pull request by glacjay**
especially for this example :-)

### CODE REVIEW

**Comment by MikeGitb** [comment]
Why? Not that I care much one way or the other., just looking for insights.

**Comment by glacjay** [comment]
@MikeGitb Because it feels a little strange if you say that the `main()` function should have a return type of `int` but doesn't actually return an `int` result, don't you think?

**Comment by johnmcfarlane** [comment]
`main` is a bit of an exception. From [cppreference.com](http://en.cppreference.com/w/cpp/language/main_function):
> The body of the main function does not need to contain the return statement: if control reaches the end of main without encountering a return statement, the effect is that of executing `return 0;`.

**Comment by glacjay** [comment]
@johnmcfarlane Oh my... didn't know that until today...

**Comment by gdr-at-ms** [comment]
Adding `return 0` would give the template this kind of code, because if you wanted to be explicit you should be using the `EXIT_SUCCESS` macro which we find overly pedantic.

**Pull request closed without merging**
