### PR TITLE
2 typos

### PR DESCRIPTION
**Pull request by Marat-Tanalin**
expecially => especially (This is expecially important for)
deafault => default (This is what a deafault == would do)
And `==` marked-up as code.

### CODE REVIEW

**Comment by blakehawkins** [comment]
31d3dac looks good, but that extra commit for the merge can be avoided by working in a separate branch and rebasing instead of automatic merging.

Probably best to leave it for now and be more careful next time.

**Comment by Marat-Tanalin** [comment]
@blakehawkins I'm not sure what you mean and how to interpret that. Could you be more specific?

FWIW, I'm not a Git guru (I usually use Mercurial without branching), so a trivial straightforward pull request is probably a maximum reasonable effort for me.

You are free to ignore my pull request and make your own one — fixing typos is only what matters here, regardless of whose exact pull request the typos are fixed as a result of.

**Comment by blakehawkins** [comment]
@Marat-Tanalin yes, no problem, and sorry if my initial message was cryptic.

> You are free to ignore my pull request and make your own one

First just want to mention that I'm not a maintainer for this repository, so it's not my duty to accept or ignore this PR. I'm just looking over it and offering my opinion - it's easier for a maintainer to accept a PR if people have already read it and agree that it looks good.

My opinion overall was that it looks good and probably isn't worth the extra hassle to fix the metadata. Instead, (in my opinion) it can just be accepted as is.

> fixing typos is only what matters here, regardless of whose exact pull request the typos are fixed as a result of.

Yes, the first goal should be to fix the main body of text, but there is value in keeping clean metadata (i.e. keeping clean commits). Take a look at the commit in your PR, 974aa65 - there's loads of code that's not written by you. There's two main reasons to avoid this - first, it's hard for people to lookup who wrote that code (it will appear as though you wrote it); second, it makes it more difficult to *revert* your commit later, in case there's an issue. This problem compounds if someone else goes and merges your merge!

> so a trivial straightforward pull request is probably a maximum reasonable effort for me.

Cool, no problem. This extra merge commit appeared because you did something like this:

* make a code change, `git commit`
* `git pull`
* send pull request

The `git pull` part "automatically" merged *the mainline* code onto your diverged version. The easiest way to avoid this is to replace the automatic merge with a rebase:

* make a code change, `git commit`
* `git fetch`
* `git rebase`
* send pull request

So there's no *need* to use a branch. The branch just makes it easier to run that rebase without worrying about losing your code in case there's a conflict.

I hope this helps :)

**Comment by Marat-Tanalin** [comment]
@blakehawkins Thanks for the clarification. FWIW, I don't deal with Git's command line at all. Is what you've described doable with GitHub's GUI (via GitHub Desktop or site)?

**Comment by blakehawkins** [comment]
I really don't know, I'm sorry. I've never used any GUI made for git.

**Comment by Marat-Tanalin** [comment]
For now, I've deleted the previous fork, created a clean new one, and created a new clean [pull request](https://github.com/isocpp/CppCoreGuidelines/pull/536). So closing this PR.

**Pull request closed without merging**
