### PR TITLE
add hunspell spell checks

### PR DESCRIPTION
**Pull request by tkruse**
This installs hunspell on travis and runs a spell-checker against all test and code comments (marked with //).

Note I am not a professor of English literature (or even native English speaker), so the dictionary of words not to be warned about may be flawed.

The travis build should fail initially with a report of failures, so probably it's best if you do not merge immediately, but wait until I add a commit with the spelling fixes. (I let this fail first so we can have a look at travis output).

### CODE REVIEW

**Comment by tkruse** [comment]
Output from failure:
https://travis-ci.org/isocpp/CppCoreGuidelines/builds/129938090
```
Line 228: unenforcable -> unenforceable
Line 4133: binarily -> ordinarily
Line 7525: synchanize -> synchronize
Line 7533: asynchroneously -> asynchronously
Line 7558: abstrcation -> abstraction
Line 7577: exectute -> execute
Line 7620: reather -> rather
Line 7621: beween -> between
Line 7673: aquired -> squired
Line 7673: consequtive -> consecutive
Line 7681: acquistion -> acquisition
Line 7767: assune -> assume
Line 7777: Detatched -> Detached
Line 7849: outlife -> outline
Line 7861: Flage -> Flag
Line 7864: reather -> rather
Line 7879: wheread -> whereas
Line 7884: sunch -> suns
Line 7892: beween -> between
Line 7917: swtiches -> switches
Line 7917: expesive -> expensive
Line 7982: suspection -> suspect ion
Line 8051: depaendency -> dependency
Line 8106: asynchroneous -> asynchronous
Line 8127: Synchrionization -> Synchronization
Line 8137: litterature -> literature
Line 8176: progrmming -> programming
Line 8192: litterature -> literature
Line 8229: catagorization -> categorization
Line 8238: objectys -> objects
Line 8264: emphemeral -> ephemeral
Line 8273: synchrnization -> synchronization
Line 10876: reinterpretcast -> reinterpret cast
Can't open -p.
make: *** [hunspell-check] Error 1
```
I think this is useful enough.

I have no idea why hunspell reports "cannot open -p", but it seems harmless. Give me until later today, and I can fix those spell mistakes.

**Comment by tkruse** [comment]
fixed few bugs in python causing missed lines, now also fixed typos in CoreGuidelines. Can be merged if you are hyppy with typo fixes and dictionary.

**Comment by browda** [comment]
In the interest of word selection, it's important to note that automated replacement can subvert the intended or presumably intended meaning.  I believe that the four words below should be changed as follows:

After looking at the changes in context, I think that
"binarily" should probably remain "binarily"
"aquired" should be "acquired" (squired has a *totally* different meaning.)
"sunch" should be "such"
"suspection" should be "suspension"
Regards

**Comment by tkruse** [comment]
There is no automatic replacement involved. The tool just shows a list of unrecognised words, and one suggestion for each. A human will have to decide each case

I replaced binarily manually, I will undo that

**Comment by tkruse** [comment]
Actually, I am not, sure, maybe hunspell -u does a replacement. I did not care, because I run it on a temporary file anyway, not the CppCoreGuidelines.md. "hunspell -u" just was the most convenient output of hunspell I could find, giving the line number and the bad word. Else hunspell can also output any bad line (but without line number), or a list of unrecognized words only (again without line number).

My second commit shows the actual changes I manually did in the CppCoreGuidelines.md, which is different from the report.

Also, I changed binarily to "binary" (not ordinarily as hunspell suggests).

**Comment by Chocobo1** [comment]
@tkruse 
You can use the following way to install `hunspell`, so the builds can retain running on container based infrastructure.

```yml
sudo: false

addons:
  apt:
    packages:
    - hunspell

install:
  -
```

https://docs.travis-ci.com/user/installing-dependencies#Adding-APT-Packages

**Comment by tkruse** [comment]
thx! made the change accordingly, rebased.

**Comment by blakehawkins** [comment]
Looks good to me.

**Comment by tkruse** [comment]
rebased, fixed more typos in 2 additional commits (original commits untouched). Remaining gailures should be fixed with #656 

Some linguist might decide which word should be used: "templated" or "templatized", I allowed both so far.

**Comment by tkruse** [comment]
See #647 #649 #651 , people are putting manual effort where a spellchecker makes life easy.

**Comment by tkruse** [comment]
rebased, after current typo fixes were merged in #679

**Pull request merged**
