### PR TITLE
C.150: exception-safety argument

### PR DESCRIPTION
**Pull request by yegord**
https://github.com/isocpp/CppCoreGuidelines/issues/136

### CODE REVIEW

**Comment by blakehawkins** [comment]
Looks good.

**Comment by thecoshman** [comment]
It might make it a bit easier to understand and see the flow of what is done when in the unsafe example if you used a number list. This still looks good enough though to me.

**Comment by yegord** [comment]
Refactored the sentence to a list. Looks indeed marginally better.

**Comment by thecoshman** [comment]
Hey, marginally better is still better. I'm actually surprised by how much clearer I think that looks, it's subjective I know, but still.

**Comment by tkoeppe** [comment]
Maybe this is off-topic in this PR, but is "[use `make_unique` to construct] objects owned by [...] other smart pointers" good advice? Surely you shouldn't construct a `shared_ptr<T>` from `make_unique<T>()`, since `make_shared<T>()` is a more efficient alternative?

**Comment by hsutter** [comment]
Thanks, accepted! I just merged it by hand because the PR was out of date (sorry for the lag) -- better than asking you to generate another PR.

**Pull request closed without merging**
