### PR TITLE
F.21 updated C++17 example

### PR DESCRIPTION
**Pull request by cubbimew**
Use square brackets, not curlies, for structured binding.
Also, this example is a perfect fit for the new if statement syntax.

### CODE REVIEW

**Comment by blakehawkins** [comment]
Looks good to me.

I think since the example is specific to c++17 the changed if-syntax is also good.

**Comment by gdr-at-ms** [comment]
Apparently, Travis CI is failing.
There is still some discussions within the C++ committee about whether to revert back to braces, or proceed with brackets with an ever increasing clever rules for disambiguation and syntax.

**Comment by cubbimew** [comment]
rebased to clear CI.
It seems like a good idea to track the syntax that is in WP ([n4606](https://github.com/cplusplus/draft/blob/master/papers/n4606.pdf)), but yes, C++17 does not yet technically exist so anything can change.. I don't mind dropping it until then.

**Comment by cubbimew** [comment]
since 39eaac7317e9aea556aab3a3480f1b6f713c0ab4 , section `[I.10](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#i10-use-exceptions-to-signal-a-failure-to-perform-a-required-task)`  uses brackets (`[val, error_code] = do_something();`), so this edit would make the guidelines internally consistent.

**Pull request merged**
