### PR TITLE
Updates to concurrency guidelines CP.21, CP.50 and CP.24

### PR DESCRIPTION
**Pull request by anthonywilliams**

### CODE REVIEW

**Comment by MikeGitb** [comment]
How far is synchronized_value in the standardization process?

**Comment by anthonywilliams** [comment]
SG1 like the synchronized_value proposal, but it hasn't gone to LWG yet.

**Comment by jwakely** [comment]
This refers to the variadic `lock_guard` but that got renamed in Issaquah, so this would need an update before merging it. Looks good to me otherwise though.

**Comment by jwakely** [comment]
I've rebased this and updated it to refer to `scoped_lock`, see https://github.com/isocpp/CppCoreGuidelines/compare/issue-762

**Comment by jwakely** [comment]
I've also pushed another commit (37d58236baa307c1d541d9d75946a1653c98468c) to fix the invalid example using `std::defer_lock` with `std::lock_guard` / `std::scoped_lock`. You don't defer the lock and then acquire it with `std::lock`, you acquire it with `std::lock` and then adopt it.

**Comment by jwakely** [comment]
Fixed at 65aa60fe1036f5e10f452aae70ec000c35ecf399 - thanks.

**Pull request closed without merging**
